### ISSUE TITLE
When reading a dataset - provide widgets that convert selected variables to some specified class by other widget

### ISSUE THREAD

**Issue by majkamichal** [majkamichal/easyPlot#18]
The idea is to give a user more flexibility when dealing with dates/datetimes  while uploading a file.

In ideal case, the user can select a list of variables to be assigned with some class defined by other widget.

That will give a full flexibility in redefining column classes.

It can also lead to errors in type casting. If this happens then some columns may become NAs and it won't be possible to change the column to a different class anymore. This will be fixed when the first version of the feature is implemented.

(The solution to the problem could be a button that creates a snapshot of data and it can be then later re-loaded. Or the app will suggest re-uploading dataset again)

**Comment by majkamichal** [comment]
See https://github.com/el-meyer/airship/issues/108#issuecomment-1809758916

**Comment by cada123** [comment]
1. Variables are selected
2. The new class is selected
3. Make sure  that an internal test is done which variable can be converted (the column won't be NA) and what not for a given class. Maybe it is possible to restrict choices of what variable can be chosen for conversion into a certain class.
4. If a convert button is pressed, there is a notification about what variables were and what variables were not converted.
